### ISSUE TITLE
UC01 – Buscar Recurso

### ISSUE THREAD

**Issue by varlen** [ESEGroup/Paraguai#1]
Permite localizar Recursos a serem agendados
Atores: Agendador

**Comment by olavosamp** [comment]
![uc01_buscar_recurso](https://cloud.githubusercontent.com/assets/5201016/21242539/f824c526-c2fb-11e6-9791-8620b8a8f1e8.jpg)

**Comment by varlen** [comment]
Faltando integrar com as telas novas

**Comment by bamorim** [comment]
Eu vou fazer tudo dde web, foca em fazer o domínio. Deixa que eu fico
responsável pela integração
