### ISSUE TITLE
UC10  – Alterar Disponibilidade de Recurso

### ISSUE THREAD

**Issue by varlen** [ESEGroup/Paraguai#11]

**Comment by olavosamp** [comment]
![uc10_alterar_disponibilidade](https://cloud.githubusercontent.com/assets/5201016/21076677/d51ecb1c-bf18-11e6-86b6-fe8388dc4ae2.jpg)

**Comment by bamorim** [comment]
Gente, alterar disponibilidade vai estar disponível para Administrador também?
