### ISSUE TITLE
UC12  – Adicionar Usuário

### ISSUE THREAD

**Issue by varlen** [ESEGroup/Paraguai#13]

**Comment by bamorim** [comment]
Vou fazer essa hoje a noite. @Lucas-CG que horas você pode fazer comigo algumas issues amanhã?
Abraços

**Comment by Lucas-CG** [comment]
@bamorim Hoje à noite também vou poder fazer algumas coisas. Dependendo da hora, posso te ajudar com essa _issue_. Amanhã, eu posso de manhã até 12h, mais ou menos, e depois à noite, por volta das 19h.

**Comment by olavosamp** [comment]
![uc12_criar_usuario](https://cloud.githubusercontent.com/assets/5201016/21076683/fda3b6f6-bf18-11e6-9d61-cdb90d14fc91.jpg)
