### ISSUE TITLE
UC14  – Remover Usuário

### ISSUE THREAD

**Issue by varlen** [ESEGroup/Paraguai#15]

**Comment by olavosamp** [comment]
![uc14_excluir_usuario](https://cloud.githubusercontent.com/assets/5201016/21076692/1aaef26a-bf19-11e6-92bb-1c6ab2f82356.jpg)

**Comment by bamorim** [comment]
@olavosamp @fmaiabatista não é melhor que o botão de remover usuário esteja dentro de uma página que mostre todos os usuários?

**Comment by bamorim** [comment]
Tipo, mostra os usuários (indice de usuários com opção de busca) em uma tabela e depois pode clicar em um usuário pra mostrar mais detalhes e depois pode clicar em deletar dentro dessa página.
Essa página de detalhes seria parecida com essa opção que tem ai em cima
