### ISSUE TITLE
Desenhar Telas Release 2

### ISSUE THREAD

**Issue by bamorim** [ESEGroup/Paraguai#19]
Desenhar a tela do layout geral (menus, etc)
Sabendo que tem duas visuaizações, a de Admin e a de Agendador

Desenhar as telas para implementar os UCs:
01, 04, 07, 08, 09, 10, 12, 13, 14

**Comment by varlen** [comment]
Já existe layout para a tela do UC01

**Comment by varlen** [comment]
Adicionei o template para a tela do UC04 conforme o documento

**Comment by fmaiabatista** [comment]
Varlen, vou padronizar as telas a partir de um template diferente do que foi feito na release 01

**Comment by varlen** [comment]
A vontade. Deem uma olhada nos templates q estão lá se quiserem. Depois
temos que definir os objetos que vão aparecer na tela.
Em 8 de dez de 2016 19:47, "Felipe Maia" <notifications@github.com>
escreveu:

**Comment by fmaiabatista** [comment]
Sim, o bernardo pediu os desenhos antes de versões implementadas para poder ir se adiantando!

![office lens 20161208-223845](https://cloud.githubusercontent.com/assets/1574224/21034048/fdd086f0-bd9b-11e6-8b00-e03c4dd40c30.jpg)
![screenshot_5](https://cloud.githubusercontent.com/assets/1574224/21034050/fdd0acd4-bd9b-11e6-83c2-6ac095618a90.png)
![screenshot_6](https://cloud.githubusercontent.com/assets/1574224/21034049/fdd07836-bd9b-11e6-9802-39928f68d026.png)
