### ISSUE TITLE
Análise FakeSiga

### ISSUE THREAD

**Issue by bamorim** [ESEGroup/Paraguai#24]
Fazer uma análise sobre integração com o FakeSiga e ideias de como implementar e repassar a informação para a equipe (por conversa ou relatório).

**Comment by bamorim** [comment]
@varlen você pode fazer isso aqui?
O ideal seria conseguir até amanhã de noite para passar tudo pra gente na quarta de manhã, será que rola?

Valeu :smile:

**Comment by varlen** [comment]
👍 
Vou começar lá pras 19h. Escrevo uma classe Wrapper pro FakeSIGA?

**Comment by bamorim** [comment]
Pode ser também, mas o mais importante é entender e compartilhar com o
grupo.

**Comment by varlen** [comment]
## Como usar o FakeSIGA

   O FakeSIGA é um serviço implementado com NodeJS acessível através de uma API REST, usando o framework [LoopBack](https://loopback.io/doc/index.html).

### Instalando
  1. Clonar do GitHub https://github.com/ESEGroup/FakeSIGA.git
  2. Instale o NodeJS se você ainda não tiver instalado
  3. Instalar as dependências com `cd FakeSIGA; npm install`
  4. Pode ser necessário instalar outras dependências e alterar algumas coisas:
     * `npm install compression`
     * `npm install cors`
     * `npm install helmet`
     * ~~Edite o arquivo `server/middleware.json` e adicione uma linha com `"/api"` abaixo de `"${restApiRoot}"`~~ É melhor atualizar o node, mas se você não ligar de usar a solução "suja" ou não funcionar mesmo assim, finge que essa linha não tá riscada.
   Aqui o node ( v 4.1.0 ) [não tem suporte](http://node.green/) a [template string](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/template_strings), quebrou o código original e todos esses passos foram necessários.
     Não verifiquei em outras versões do Node então pode ser que em alguma versão essas ou algumas dessas bibliotecas já venham instaladas ou já estavam instaladas globalmente no computador do Fábio e ele não incluiu no `package.json`
  5. Após instalar/modificar tudo pra rodar, inicie o servidor com `node server/server`
  6. A API REST pode ser explorada através de http://0.0.0.0:3000/explorer quando o serviço estiver rodando.

### API REST
  1. **GET** http://0.0.0.0:3000/ApiStatus retorna o estado do servidor
```
    {
        started : Horário de inicio da API no formato ISO8601,
        uptime : Tempo em segundos da API online
    }
```

  2. **GET** http://0.0.0.0:3000/api/Dados retorna os dados de todos os usuários
```
{
        "CPF": string,
        "Matricula": string,
        "Nome": string,
        "DataNascimento": dd/mm/aaaa,
        "Aluno": booleano,
        "Professor": booleano,
        "ProfessorVisitante": booleano,
        "FuncionarioAdministrativo": booleano,
        "FuncionarioTerceirizado": booleano,
        "id": inteiro
}
```
  3. **GET** `http://0.0.0.0:3000/api/Dados/<id>` retorna o dado de um usuário específico aonde `<id>` é um inteiro
  4. **GET** `http://0.0.0.0:3000/api/Dados?filter=<filtro>` pode ser utilizado para buscar ou retornar uma entrada específica aonde `<filtro>` pode ser um JSON como o abaixo [http://www.w3schools.com/tags/ref_urlencode.asp](codificado para URL)
`
    {"where": { "ProfessorVisitante":true} }
`
    A referência completa para filtros pode ser encontrada em https://loopback.io/doc/en/lb2/Querying-data.html#using-stringified-json-in-rest-queries
  5. Outras chamadas podem ser vistas através do explorer ( http://0.0.0.0:3000/explorer )
  6. Outro Endpoint implementado é a [autenticação](https://loopback.io/doc/en/lb2/Introduction-to-User-model-authentication.html) de usuário. Essa autenticação pode ser feita através de um **POST** para `/api/Users/login` contendo:
```
{
     "email": "ffarzat@cos.ufrj.br",
     "password": "123456"
}
```

  Possivelmente, utilizaremos isso para implementar autenticação no nosso sistema e pegaremos os dados do endpoint de dados para ver o nível de acesso de cada usuário.
