### ISSUE TITLE
Descrever API de Agendamento e Mudança de Estado de Recurso

### ISSUE THREAD

**Issue by bamorim** [ESEGroup/Paraguai#25]
O grupo @ESEGroup/grupo-uruguai precisa disso ASAP.
Alguem pode me ajudar com isso?

Podemos usar essa issue mesmo para discutir.

Minha sugestão, dois endpoints:

POST /recursos/:id_recurso:/agendamentos para criar agendamentos
GET /recursos/:id_recurso:/agendamentos para obter agendamentos
POST /recursos/:id_recurso:/estado para mudar o estado utilizavel/não utilizavel

Podemos usar form data ou json, os campos seriam:
```json
{
  "agendamento": {
    "periodo": {
      "inicio": "2016-12-05T12:00:00Z",
      "fim": "2016-12-05T14:00:00Z"
    }
  }
}
```

O inicio/fim nesse caso está no formato ISO8601, podemos também usar unix epoch (inteiro, segundos desde 01/01/1970), mas acho esse formato mais readable.

Se fosse form data, os campos seriam: agendamento[periodo][inicio] e agendamento[periodo][fim]

Para o estado, podemos apenas colocar:
```json
{ "utilizavel": true/false }
```
Ou form data com o campo utilizavel=true/false.

O userId é inferido da chave de autenticação.
Falando em autenticação, temos as opções:

* Token como parametro uri (?token=XXXX),
* Token no header de authorization (Authorization: Bearer XXXX)

**Comment by varlen** [comment]
Acho que podemos deixar o token na uri mesmo por simplicidade. Data assim tá ok também, dá pra parsear sem dor e não tem a ilegibilidade do unixtime. Por mim, podemos fechar essa api pra eles mockarem.

**Comment by bamorim** [comment]
@ESEGroup/grupo-uruguai, em especial, @brenoarosa, essa vai ser a API para vocês integrarem, assim que possível eu vou mandar pra vocês qual vai ser o endpoint certo, mas a estrutura de dados vai ser essa.

Abraços
