### ISSUE TITLE
UC07  – Cadastrar Recurso

### ISSUE THREAD

**Issue by varlen** [ESEGroup/Paraguai#8]

**Comment by bamorim** [comment]
@varlen 
No domínio, tudo de CRUD de Recurso fica no serviço CRUD recurso, lembre-se de fazer dependency injection do repositorio.
Crie uma branch crud-recurso para resolver as issues de crud: #1, #9 e esse daqui (#8)

Na web, eu recomendo seguir rotas restful:
GET /admin/recursos/ (indices de todos os recurso)
GET /admin/recursos/:id: (Ver o recurso em detalhes, **se necessário**)
GET /admin/recursos/novo (Formulário de criar recurso)
POST /admin/recursos (Criar recurso)
POST ou PUT /admin/recursos/:id: (Alterar recurso)
Sobre POST ou PUT, depende se o content-body vai ser o recurso inteiro.

Você vai ter que fazer também alguma forma de termos os tipos de recurso possíveis.

**Comment by olavosamp** [comment]
![uc07_criar_recurso](https://cloud.githubusercontent.com/assets/5201016/21076672/b86d9ebc-bf18-11e6-91f6-f7a543a6dfe3.jpg)
